version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    volumes:
      - ./src:/app/src
    ports:
      - "${APP_PORT:-3000}:3000"
    networks:
      - local_network
      - app_network
    depends_on:
      - redis
      - postgres  

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "${SERVER_PORT:-8080}:80"
      - "${SERVER_SSL_PORT:-443}:443"
    depends_on: 
      - app  
    volumes:
      - ./:/var/www
      - ${NGINX_CONF}:/etc/nginx/conf.d/
    networks:
      - local_network
      - app_network

  redis:
    container_name: redis
    image: redis:5
    networks:
      - local_network

  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - local_network
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data


  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-DevPgAdmin4}
      PGADMIN_LISTEN_PORT: 9000
    ports:
      - "127.0.0.1:${PGADMIN_PORT:-9000}:9000"
    volumes:
      - pgadmin-data:/root/.pgadmin
    networks:
      - local_network  



networks:
    local_network:
      driver: bridge
    app_network:
      driver: bridge
      external: true


volumes:
  pgdata:
    driver: local
  pgadmin-data:
    driver: local